# Generated by Django 5.2.1 on 2025-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
