# Generated by Django 5.2.1 on 2025-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
