# Generated by Django 5.2.1 on 2025-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_last_started_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='last_started_at',
            new_name='finished_at',
        ),
        migrations.AddField(
            model_name='game',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
