# Generated by Django 5.2.1 on 2025-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_last_started_at_game_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for second player'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
