# Generated by Django 5.1.2 on 2025-05-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_word_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.word'),
        ),
    ]
