# Generated by Django 5.1.2 on 2025-05-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_game_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playergame',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
