# Generated by Django 5.2.1 on 2025-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_playergame_hint_used_playergame_hints_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='letter_hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
