# Generated by Django 5.2.1 on 2025-05-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_playergame_letter_hint_used_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=10),
        ),
    ]
