# Generated by Django 5.2.1 on 2025-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_word_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
    ]
